### ISSUE TITLE
Implement EIP-1186 Node Decoding for `VerifyEthereumProofs`

### ISSUE THREAD

**Issue by seunlanlege** [polytope-labs/solidity-merkle-trees#10]
This requires implementing RLP decoding and implementing the proper node decoding logic here: 

https://github.com/polytope-labs/solidity-merkle-trees/blob/main/src/trie/ethereum/EthereumTrieDB.sol

**Comment by ripa1995** [comment]
@seunlanlege I'd like to work on that, ok for you?

As far as I understood, I just need to follow [RLP](https://ethereum.org/en/developers/docs/data-structures-and-encoding/rlp/#definition) definition for encoding and apply it to decoding, correct?

**Comment by seunlanlege** [comment]
> @seunlanlege I'd like to work on that, ok for you?
> 
> 
> 
> As far as I understood, I just need to follow [RLP](https://ethereum.org/en/developers/docs/data-structures-and-encoding/rlp/#definition) definition for encoding and apply it to decoding, correct?

Yeah feel free. The task is just RLP node decoding, you could also just use a battle tested library for decoding.

**Comment by ripa1995** [comment]
> > @seunlanlege I'd like to work on that, ok for you?
> > As far as I understood, I just need to follow [RLP](https://ethereum.org/en/developers/docs/data-structures-and-encoding/rlp/#definition) definition for encoding and apply it to decoding, correct?
> 
> Yeah feel free. The task is just RLP node decoding, you could also just use a battle tested library for decoding.

I'm currently using this [RLPReader](https://github.com/hamdiallam/Solidity-RLP/blob/master/contracts/RLPReader.sol) library.
I'm able to retrieve the node kind, but probably i'm missing something for the keys of each node. Maybe I have to implement this [from_compact](https://github.com/citahub/cita-trie/blob/6dd02de9f27d2384e083916dfceb30fae322bdd6/src/nibbles.rs#L25-L50) in order to obtain the actual key?

**Comment by ripa1995** [comment]
> You'll need to read the EIP-1186 spec. The node kind should be in the first few bytes of the node rlp

The node kind is not an issue, I'm doing it following [Patricia Merkle Trie - Optimization](https://ethereum.org/en/developers/docs/data-structures-and-encoding/patricia-merkle-trie/#optimization) and [Patricia Merkle Trie - Specification](https://ethereum.org/en/developers/docs/data-structures-and-encoding/patricia-merkle-trie/#specification).

The issue i'm having now is while decoding the actual nodes, I'm probably not removing / transforming some of the bytes decoded.

**Comment by seunlanlege** [comment]
> The issue i'm having now is while decoding the actual nodes, I'm probably not removing / transforming some of the bytes decoded.

Here's a working rust implementation for node decoding to guide your implementation: https://github.com/polytope-labs/ethereum-triedb/blob/main/src/node_codec.rs

**Comment by ripa1995** [comment]
> > The issue i'm having now is while decoding the actual nodes, I'm probably not removing / transforming some of the bytes decoded.
> 
> Here's a working rust implementation for node decoding to guide your implementation: https://github.com/polytope-labs/ethereum-triedb/blob/main/src/node_codec.rs

That was very helpful, thank you.
Currently I'm able of decoding the nodes, still I'm having some issues with the `key` of leaf nodes and its comparison with the key provided to the verification function. I.e., if I try to verify the proof that is used in the test function of `ethereum-triedb` repository, I get the following result:
```javascript
decoded_leaf_key= 0x3c3738deb88e49108e7a5bd83c14ad65b5ba598e2932551dc9b9ad1879;
input_key= 0x3483bb4c3738deb88e49108e7a5bd83c14ad65b5ba598e2932551dc9b9ad1879;
```
As you can see there is a prefix that makes the two different. I will try to understand better what transformation is needed to be performed by looking at [cita-trie](https://github.com/citahub/cita-trie) and [Patricia Merkle Trie](https://ethereum.org/en/developers/docs/data-structures-and-encoding/patricia-merkle-trie/).

Will keep you updated and will open a PR if I succeed.
