### ISSUE TITLE
[mmr] Use iterator for MmrLeaves

### ISSUE THREAD

**Issue by seunlanlege** [polytope-labs/solidity-merkle-trees#32]
When getting the leaves for a subtree, we copy into two new arrays. We can avoid this by using an iterator that sets the offset and length for subtree leaves.

**Comment by CJ13th** [comment]
Hey @seunlanlege, is this issue still relevant? If it is, I think it could make a "good first issue" for one of the Polkadot Blockchain Academy alumni to work on during morekudos.com/carnival.

**Comment by seunlanlege** [comment]
Hi yes it's still relevant

**Comment by CJ13th** [comment]
Great! 

I've deployed a Hyperbridge project page [morekudos.com/projects/hyperbridge](https://www.morekudos.com/projects/hyperbridge)

Going forward, any open issues labelled as `good first issue` from the repos listed on your project page will automatically appear in the table.

The Kudos Carnival is a 6 week issue solving competition with the aim of getting more PBA alumni contributing to the ecosystem, so feel free to label some existing issues or generate new ones. Issues of all types are being requested, some good categories could be:

- Building example Dapps using your team’s SDK or tech stack
- Improving documentation
- Bug fixing
- Polishing existing features / UI
- New feature requests

**Comment by seunlanlege** [comment]
Hi @CJ13th  can you also add this repo

https://github.com/polytope-labs/sc-simnode

**Comment by CJ13th** [comment]
@seunlanlege Added!

**Comment by Krayt78** [comment]
Hello @seunlanlege, i took some time to implement this change, its in this PR #43.
Let me know if any changes are needed or if i didnt understand the issue in the first place xD

**Comment by seunlanlege** [comment]
Apologies for the delay @Krayt78. Taking a look now
