### ISSUE TITLE
can you upgrade your npm version ?

### ISSUE THREAD

**Issue by GalaxySciTech** [polytope-labs/solidity-merkle-trees#35]
<img width="757" alt="image" src="https://github.com/polytope-labs/solidity-merkle-trees/assets/30950645/a2f06ba3-2bc2-4be0-aee1-8a564a52075e">

**Comment by seunlanlege** [comment]
Will handle this

**Comment by GalaxySciTech** [comment]
tell me pls when handled

> Will handle this

**Comment by seunlanlege** [comment]
> tell me pls when handled

Published v0.2.1

https://www.npmjs.com/package/@polytope-labs/solidity-merkle-trees/v/0.2.1
